plugins { id 'com.android.application' }

android { namespace 'ir.ansarweb.hesabbourse'

compileSdk 36

defaultConfig {
    applicationId 'ir.ansarweb.hesabbourse'

    minSdk 24
    targetSdk 36

    versionCode 5
    versionName "2.3"
}

def ksFile = System.getenv("KEYSTORE_FILE")
def ksPassword = System.getenv("KEYSTORE_PASSWORD")
def ksAlias = System.getenv("KEY_ALIAS")

signingConfigs {
    release {
        if (ksFile && ksPassword && ksAlias) {
            storeFile = file(ksFile)
            storePassword = ksPassword
            keyAlias = ksAlias
            keyPassword = ksPassword
        }
    }
}

buildTypes {
    release {
        signingConfig = signingConfigs.release
    }
}
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
